### ISSUE TITLE
asa_acls Duplicate Element Doesn't Fail or Move Correctly

### ISSUE THREAD

**Issue by timway** [ansible-collections/cisco.asa#127]
##### SUMMARY

When specifying a `line` in the ACE entry the module reports changed if that ACE is not present at that line but fails to correctly move it. This makes the play not idempotent because each run will report changed and fail to move the line successfully.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/darkhelmet/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/darkhelmet/.venvs/py2-tower-3.8.3/lib/python3.9/site-packages/ansible
  executable location = /home/darkhelmet/.venvs/py2-tower-3.8.3/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
```

##### COLLECTION VERSION

```paste below
# /home/darkhelmet/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.asa  2.0.2  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ASAv 9.12(4)

##### STEPS TO REPRODUCE

On the ASA create an ACL like:

```
access-list abcd extended permit ip any4 host 1.1.1.1 
access-list abcd extended permit ip any4 host 8.8.8.8 
access-list abcd extended permit ip any4 host 9.9.9.9
```

Then use `merged` to add a line at position 2:

```yaml
    - cisco.asa.asa_acls:
        config:
          acls:
            - name: abcd
              acl_type: extended
              aces:
                - grant: deny
                  line: 2
                  protocol_options:
                    ip: true
                  source:
                    any4: true
                  destination:
                    host: 8.8.4.4
        state: merged
```

Go on the CLI of the ASA and add an ACL entry at line 2 (that pushes the one we just added to line 2)

```
access-list abcd line 2 extended deny ip any4 host 1.0.0.1
```

Then run the above play again. You'll see it tries to run:

```json
    "commands": [
        "access-list abcd line 2 extended deny ip any4 host 8.8.4.4"
    ],
```

##### EXPECTED RESULTS

Ideally, the playbook removes the line and re-adds it which allows the play to truly "change" successfully. Because it may change a live ACL on the device that "could" affect management it may be preferential to "fail" out and allow the playbook author to handle the move separately. Either solutions are alright in the long run. Right now it's just not idempotent because the move fails.

##### ACTUAL RESULTS

It results in the following at the CLI:

```
ciscoasa(config)# access-list abcd line 2 extended deny ip any4 host 8.8.4.4
WARNING: <abcd> found duplicate element
access-list abcd line 2 extended deny ip any4 host 8.8.4.4
```

The task reports "changed" and moves on.

@nj344170w and @russ-jenkins
