### ISSUE TITLE
Cisco ASA ACLs module fails when tryinng to configure ICMP/ICMP6 option

### ISSUE THREAD

**Issue by justjais** [ansible-collections/cisco.asa#15]
##### SUMMARY

Cisco ASA ACLs module fails when tryinng to configure ICMP/ICMP6 option
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

asa_acls.py
##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- cisco.asa.asa_acls:
  config:
    - acls:
      - name: test_access
        acl_type: extended
        aces:
          - grant: deny
            line: 1
            protocol: tcp
            protocol_options:
              tcp: true
            source:
              address: 192.0.2.0
              netmask: 255.255.255.0
            destination:
              address: 192.0.3.0
              netmask: 255.255.255.0
              port_protocol:
                eq: www
            log: default
          - grant: deny
            line: 2
            protocol: icmp
            protocol_options:
              icmp:
                alternate_address: true
            source:
              address: 198.51.100.0
              netmask: 255.255.255.0
            destination:
              address: 198.51.110.0
              netmask: 255.255.255.0
            log: errors
  state: merged
```

##### EXPECTED RESULTS

The config command is generated properly and ACLs configured as expected

##### ACTUAL RESULTS

Command generated has missing ICMP option and thus generated command fails

```paste below

```
