### ISSUE TITLE
[cisco.asa.asa_ogs] module execution fails on ASA configuration with object group named with only digits

### ISSUE THREAD

**Issue by yaroslavhlushko** [ansible-collections/cisco.asa#153]
##### SUMMARY
When trying to use module cisco.asa.asa_ogs to manage object groups it fails if the ASA has an object group with only digits in its name.
e.g.
```ASA code
object-group service 3300 tcp
 port-object eq 3300
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.asa.asa_ogs
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.9] 
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
cisco.asa  2.1.0 
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING = False
SHOW_CUSTOM_STATS = True
```

##### OS / ENVIRONMENT

Cisco ASA OS version 9.9(2)32 (and many other)

##### STEPS TO REPRODUCE

Try to make any change in object group configuration in case the ASA config has an object group named with only digits

```yaml
---
- hosts: asa_edge
  gather_facts: false

  tasks:
  - name: Sync MS Subnets object configuration with all Firewalls
    cisco.asa.asa_ogs:
      config:
      - object_type: network
        object_groups:
          - name: ms-subnets
            network_object:
              address: "{{ lookup('file', '~/ms-subnets-objects.txt').splitlines() }}"
      state: replaced
    when: ansible_network_os == 'cisco.asa.asa'
    tags: obj-grp

  - name: save running to startup when modified
    cisco.asa.asa_config:
      save_when: modified
```

##### EXPECTED RESULTS

Configuration should be changed as it does when the ASA config does not have this object group
After removing this object group it works as expected
```
no object-group service 3300 tcp
```
##### ACTUAL RESULTS

The module execution fails with these errors:

```paste below
File "/tmp/ansible_cisco.asa.asa_ogs_payload_y2yrt7w1/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 133, in get_network_resources_facts
    inst.populate_facts(
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_y2yrt7w1/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/ogs/ogs.py", line 89, in populate_facts
  
  "msg": "'<' not supported between instances of 'int' and 'str'
```

My assumption is that it tries to sort object groups, most of which are of 'str' type and this one is 'int'
From the file cisco/asa/plugins/module_utils/network/asa/facts/ogs/ogs.py (line 89)
```
config_dict["object_groups"] = sorted(
	config_dict["object_groups"],
	key=lambda k, sk="name": k[sk],
)
```
