### ISSUE TITLE
[cisco.asa.asa_ogs] Incorrect service object groups created (2 instead of 1)

### ISSUE THREAD

**Issue by miff2000** [ansible-collections/cisco.asa#166]
##### SUMMARY

When I check the `rendered` output from the `asa_ogs` module, I see two `object-group`s of type `service` are created. The first has no protocol specified, and the second has type `tcp`.

```json
    "add_missing_ogs": {
        "changed": false,
        "failed": false,
        "rendered": [
            "object-group service ukfast.enterprise-director.inbound.ports.tcp",
            "object-group service ukfast.enterprise-director.inbound.ports.tcp tcp",
            "port-object eq ssh",
            "port-object eq 2020",
            "port-object eq 5986",
            "port-object eq 6093",
            "port-object eq 8443"
        ]
    }
```

The line `object-group service ukfast.enterprise-director.inbound.ports.tcp` should not have been rendered.

Here's the module input:

```yaml
        - object_type: service
          object_groups:
          - name: allowed.ports.tcp
            protocol: tcp
            port_object:
            - eq: ssh
            - eq: 2020
            - eq: 5986
            - eq: 6093
            - eq: 8443
            - range:
                start: 9101
                end: 9103
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
cisco.asa
```

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.12.4]
  executable location = /home/user/.pyenv/versions/ansible-2.12/bin/ansible
  python version = 3.8.6 (default, Mar 21 2021, 17:50:29) [GCC 9.3.0]
  jinja version = 3.1.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
cisco.asa  3.0.0
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/user/projects/network-automation/ansible-network-automation/ansible.cfg) = ['/home/user/projects/network-automation/ansible-network-automation/inventory/hosts.ini']
DEFAULT_TIMEOUT(/home/user/projects/network-automation/ansible-network-automation/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/user/projects/network-automation/ansible-network-automation/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/user/projects/network-automation/ansible-network-automation/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco ASA OS version 9.9(2)32 (and many others)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: asa_edge
  gather_facts: false

  tasks:
 - name: Add the OGs and ACLs
    when:
    - writable_device
    - not og_already_exists
    block:
    - name: Add missing Object Groups
      cisco.asa.asa_ogs:
        state: rendered
        config:
        - object_type: service
          object_groups:
          - name: allowed-ports.tcp
            protocol: tcp
            port_object:
            - eq: 22
            - eq: 2020
            - eq: 5986
            - eq: 6093
            - eq: 8443
            - range:
                start: 9101
                end: 9103
```

The rendered output is shown below.

##### EXPECTED RESULTS

```json
ok: [asa_edge] => {
    "add_missing_ogs": {
        "changed": false,
        "failed": false,
        "rendered": [
            "object-group service allowed-ports.tcp tcp",
            "port-object eq ssh",
            "port-object eq 2020",
            "port-object eq 5986",
            "port-object eq 6093",
            "port-object eq 8443",
            "port-object range 9101 9103"
        ]
    }
}
```

##### ACTUAL RESULTS

```json
ok: [asa_edge] => {
    "add_missing_ogs": {
        "changed": false,
        "failed": false,
        "rendered": [
            "object-group service allowed-ports.tcp",
            "object-group service allowed-ports.tcp tcp",
            "port-object eq ssh",
            "port-object eq 2020",
            "port-object eq 5986",
            "port-object eq 6093",
            "port-object eq 8443",
            "port-object range 9101 9103"
        ]
    }
}
```
