### ISSUE TITLE
The collection bindep is hardcoding python version

### ISSUE THREAD

**Issue by lucas-benedito** [ansible-collections/cisco.asa#197]
##### SUMMARY
While installing the collection and using the bindep offered by the same, my build ended up installing python38 due to the hardcoded bindep with python38-Cython

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
task

##### ANSIBLE VERSION
```
ansible-core 2.14
ansible-builder 1.2.0
```

##### COLLECTION VERSION
```
version: "4.0.0"
```

##### CONFIGURATION
```
Default config
```

##### OS / ENVIRONMENT
```
RHEL 8.7
```

##### STEPS TO REPRODUCE
Building Execution Environment using ansible-builder with the files below
```
execution-environment.yml 
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest

ansible_config: 'ansible.cfg' 

dependencies:
  galaxy: requirements.yml

```

```
requirements.yml
---
collections:
  - name: cisco.asa
    version: "4.0.0"
```

##### EXPECTED RESULTS
```
Dependencies installed from Python 3.9
```

##### ACTUAL RESULTS
```
- 'python38-Cython [compile platform:centos-8 platform:rhel-8]  # from collection   cisco.asa'
```
