### ISSUE TITLE
asa_ogs: description change might be ignored

### ISSUE THREAD

**Issue by rulev** [ansible-collections/cisco.asa#260]
##### SUMMARY
In some situations description change might be ignored

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.asa.asa_ogs

##### STEPS TO REPRODUCE
before:
```
object-group network test_group
 description a test group
 group-object group_1
 group-object group_2
```
```yaml
  - cisco.asa.asa_ogs:
        state: replaced
        config:
          - object_type: network
            object_groups:
              - name: test_group
                description: test group
                group_object:
                  - group_1
                  - group_2
```

##### EXPECTED RESULTS
description should be changed
command fired:
```
object-group network test_group
description test group
```

##### ACTUAL RESULTS
description won't be changed
command fired:
```
object-group network test_group
no group-object group_1
no group-object group_2
```
