### ISSUE TITLE
save_when feature

### ISSUE THREAD

**Issue by su-hy** [ansible-collections/cisco.asa#44]
##### SUMMARY
It would be nice if asa_config module had save_when functionality present in ios_config module. 
https://docs.ansible.com/ansible/latest/modules/ios_config_module.html#parameter-save_when

##### ISSUE TYPE
I would like to be able to save config only if it has been modified. 

##### COMPONENT NAME
asa_config

##### ADDITIONAL INFORMATION
It would work exactly like it works on ios_config, including the diff_ignore_lines

```yaml
tasks:
   - name: Save config to flash if it has been modified.
     ios_config:
      diff_against: startup
      diff_ignore_lines:
       - '[a-zA-Z0-9]{8}\s[a-zA-Z0-9]{8}\s.*'
       - 'certificate self-signed 01'
       - 'quit'
      save_when: modified
```
