### ISSUE TITLE
State: replaced not replacing all lines of ACL

### ISSUE THREAD

**Issue by busseax** [ansible-collections/cisco.asa#82]
##### SUMMARY
When running a playbook to replace a certain ACL with new/modified lines it leaves orphaned lines behind without deleting them.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

asa_acls

##### ANSIBLE VERSION

```
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abusse/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT

Debian 10.6
ASA is running version 9.9(1)2

##### STEPS TO REPRODUCE

Collections used:
```
ansible.netcommon:1.4.2-dev2
cisco.asa:1.0.4
```

Before state:
```
# sh access-list ansible_test
access-list ansible_test; 3 elements; name hash: 0x1b2b1138
access-list ansible_test line 1 remark HostA
access-list ansible_test line 2 extended deny ip host 1.1.1.1 any4 (hitcnt=0) 0xc24d3351
access-list ansible_test line 3 remark HostB
access-list ansible_test line 4 extended permit ip host 2.2.2.2 any4 (hitcnt=0) 0x44cd4b7e
access-list ansible_test line 5 remark HostC
access-list ansible_test line 6 extended permit ip host 3.3.3.3 any4 (hitcnt=0) 0x4c8c99d5
```

Playbook used:

```yaml
---
- hosts: devpn

  connection: network_cli
  gather_facts: no
  become: yes
  become_method: enable
  vars_files:
    - ./svc_credentials.yml

  collections:
    - cisco.asa

  tasks:
    - name: "TASK 1: Create ansible_test ACL"
      asa_acls:
        config:
          acls:
          - name: ansible_test
            acl_type: extended
            aces:
              - line: 1
                remark: HostA0
              - grant: deny
                line: 2
                protocol: ip
                source:
                  host: 1.1.1.1
                destination:
                  any4: true
              - line: 3
                remark: HostB1
              - grant: permit
                line: 4
                protocol: ip
                source:
                  host: 2.2.2.2
                destination:
                  any4: true
              - line: 5
                remark: HostC2
              - grant: permit
                line: 6
                protocol: ip
                source:
                  host: 3.3.3.3
                destination:
                  any4: true
        state: replaced
```

##### EXPECTED RESULTS

```
# sh access-list ansible_test
access-list ansible_test; 3 elements; name hash: 0x1b2b1138
access-list ansible_test line 1 remark HostA0
access-list ansible_test line 2 extended deny ip host 1.1.1.1 any4 (hitcnt=0) 0xc24d3351
access-list ansible_test line 3 remark HostB1
access-list ansible_test line 4 extended permit ip host 2.2.2.2 any4 (hitcnt=0) 0x44cd4b7e
access-list ansible_test line 5 remark HostC2
access-list ansible_test line 6 extended permit ip host 3.3.3.3 any4 (hitcnt=0) 0x4c8c99d5
```

##### ACTUAL RESULTS

The ACL has been partially updated but left old remarks behind.

```paste below
# sh access-list ansible_test
access-list ansible_test; 3 elements; name hash: 0x1b2b1138
access-list ansible_test line 1 remark HostAA
access-list ansible_test line 2 remark HostA
access-list ansible_test line 3 remark HostBB
access-list ansible_test line 4 extended deny ip host 1.1.1.1 any4 (hitcnt=0) 0xc24d3351
access-list ansible_test line 5 remark HostCC
access-list ansible_test line 6 remark HostB
access-list ansible_test line 7 extended permit ip host 2.2.2.2 any4 (hitcnt=0) 0x44cd4b7e
access-list ansible_test line 8 remark HostC
access-list ansible_test line 9 extended permit ip host 3.3.3.3 any4 (hitcnt=0) 0x4c8c99d5
```
