### ISSUE TITLE
Ansible_net_model is not returned in facts

### ISSUE THREAD

**Issue by Aidar5** [ansible-collections/cisco.asa#86]
##### SUMMARY

Return value "ansible_net_model" is absent when requesting ASA facts via CISCO ASA Ansible Collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.asa.asa_facts – Collect facts from remote devices running Cisco ASA

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/collections']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
```

##### OS / ENVIRONMENT

For example: Cisco ASA5508, Cisco FPR2110

##### STEPS TO REPRODUCE

Get facts from device using "cisco.asa.asa_facts" plugin

```yaml
- hosts: asa
  connection: network_cli
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    ansible_user: name
    ansible_ssh_pass: passwd
    ansible_become: true
    ansible_become_method: ansible.netcommon.enable
    ansible_become_pass: become_password
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.asa.asa

  collections:
    - cisco.asa

  tasks:
    - name: Gather all legacy facts
      asa_facts:
        gather_subset: all
```

##### EXPECTED RESULTS

I expect to see "ansible_net_model" in returned value as it stated in documentation https://docs.ansible.com/ansible/2.10/collections/cisco/asa/asa_facts_module.html

##### ACTUAL RESULTS

"ansible_net_model" is not seen in response.

```paste below
```
